### PR TITLE
Keep at least 3 empty lines

### PR DESCRIPTION
**Pull request by sdegutis**
Empty lines are important to some people in views. I'd like to keep my empty lines. This one PR would make this extension pretty much perfect for me. Thanks.

### CODE REVIEW

**Comment by Red-ZT** [comment]
Good. however there might be people who don't want this. I guess it is better to add a config.

**Comment by eseom** [comment]
Good. however there might be people who don't want this. I guess it is better to add a config.

**Comment by sdegutis** [comment]
Also a config for the new_line option, then. Or maybe just a config to let us pass options through to prettydiff directly.

**Comment by eseom** [comment]
We need own config properties, I will work soon

**Comment by eseom** [comment]
added the configuration!

**Pull request closed without merging**
